export const SET_PLAYER_REQUEST = 'SET_PLAYER_REQUEST'
export const SET_PLAYER_SUCCESS = 'SET_PLAYER_SUCCESS'
export const SET_PLAYER_FAIL = 'SET_PLAYER_FAIL'

export const CONNECT_PLAYER_REQUEST = 'CONNECT_PLAYER_REQUEST'
export const CONNECT_PLAYER_SUCCESS = 'CONNECT_PLAYER_SUCCESS'
export const CONNECT_PLAYER_FAIL = 'CONNECT_PLAYER_FAIL'

export const SET_TRACK = 'SET_TRACK'
export const SET_PAUSE = 'SET_PAUSE'
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE'

export const PLAY_SONG_REQUEST = 'PLAY_SONG_REQUEST'
export const PLAY_SONG_SUCCESS = 'PLAY_SONG_SUCCESS'
export const PLAY_SONG_FAIL = 'PLAY_SONG_FAIL'

export const SET_PLAYBACK_VOLUME_SUCCESS = 'SET_PLAYBACK_VOLUME_SUCCESS'
export const SET_PLAYBACK_VOLUME_FAIL = 'SET_PLAYBACK_VOLUME_FAIL'

export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS'
export const LIKE_SONG_RESET = 'LIKE_SONG_RESET'
export const LIKE_SONG_FAIL = 'LIKE_SONG_FAIL'

export const UNLIKE_SONG_SUCCESS = 'UNLIKE_SONG_SUCCESS'
export const UNLIKE_SONG_RESET = 'UNLIKE_SONG_RESET'
export const UNLIKE_SONG_FAIL = 'UNLIKE_SONG_FAIL'

export const TOGGLE_SHUFFLE_SUCCESS = 'TOGGLE_SHUFFLE_SUCCESS'
export const TOGGLE_SHUFFLE_FAIL = 'TOGGLE_SHUFFLE_FAIL'

export const TOGGLE_REPEAT_SUCCESS = 'TOGGLE_REPEAT_SUCCESS'
export const TOGGLE_REPEAT_FAIL = 'TOGGLE_REPEAT_FAIL'

export const LOG_OUT = 'LOG_OUT'
