export const GET_MY_PROFILE_REQUEST = 'GET_MY_PROFILE_REQUEST'
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS'
export const GET_MY_PROFILE_FAIL = 'GET_MY_PROFILE_FAIL'

export const GET_MY_PLAYLISTS_REQUEST = 'GET_MY_PLAYLISTS_REQUEST'
export const GET_MY_PLAYLISTS_SUCCESS = 'GET_MY_PLAYLISTS_SUCCESS'
export const GET_MY_PLAYLISTS_FAIL = 'GET_MY_PLAYLISTS_FAIL'

export const GET_MY_LIKED_SONG_REQUEST = 'GET_MY_LIKED_SONG_REQUEST'
export const GET_MY_LIKED_SONG_SUCCESS = 'GET_MY_LIKED_SONG_SUCCESS'
export const GET_MY_LIKED_SONG_FAIL = 'GET_MY_LIKED_SONG_FAIL'

export const GET_PLAYLIST_REQUEST = 'GET_PLAYLIST_REQUEST'
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS'
export const GET_PLAYLIST_FAIL = 'GET_PLAYLIST_FAIL'

export const GET_ARTIST_REQUEST = 'GET_ARTIST_REQUEST'
export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS'
export const GET_ARTIST_FAIL = 'GET_ARTIST_FAIL'
